name: preop3
channels:
  - brittainhard
  - anaconda
  - conda-forge
  
dependencies:
  - python=3.6
  - fancyimpute
  - scikit-learn=0.19.1
  - pandas
  - numpy
  - matplotlib
  - imbalanced-learn
  - xgboost
  - jupyterlab
  - nb_conda_kernels
  - seaborn
  - dill=0.2.7.1
  - pillow
  - tqdm
